# Generated by Django 3.1.1 on 2020-09-20 05:15

from django.db import migrations, models
import djongo.models.fields
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, editable=False)),
                ('number', models.AutoField(help_text='Invoice Number', primary_key=True, serialize=False)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('reference_number', models.CharField(help_text='Enter Reference Number/PO', max_length=30)),
                ('reference_date', models.DateField(help_text='PO/Order Date')),
                ('addressed_to', models.CharField(help_text='Invoice Addressed To', max_length=300)),
                ('party_gst', models.CharField(blank=True, help_text='GST Number of buyer', max_length=15)),
                ('modified_at', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, help_text='Additional Notes', max_length=1000)),
                ('items', djongo.models.fields.ArrayField(model_container=invoice.models.Item)),
                ('s_gst', models.IntegerField(default=9, help_text='S_GST Percentage')),
                ('c_gst', models.IntegerField(default=9, help_text='C_GST Percentage')),
                ('other_charges', models.IntegerField(help_text='Other Charges as needed')),
                ('total', models.IntegerField(help_text='Invoice Total')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
